"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProductType = void 0;
exports.ProductType = {
    Savings: "savings",
    Checking: "checking",
    Cd: "cd",
    Ira: "ira",
    Loan: "loan",
    CreditCard: "creditCard",
};
