"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApitureApiTimeoutError = void 0;
class ApitureApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, ApitureApiTimeoutError.prototype);
    }
}
exports.ApitureApiTimeoutError = ApitureApiTimeoutError;
