"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApitureApiError = void 0;
class ApitureApiError extends Error {
    statusCode;
    body;
    constructor({ message, statusCode, body }) {
        super(message);
        Object.setPrototypeOf(this, ApitureApiError.prototype);
        if (statusCode != null) {
            this.statusCode = statusCode;
        }
        if (body !== undefined) {
            this.body = body;
        }
    }
}
exports.ApitureApiError = ApitureApiError;
