"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferState = void 0;
exports.TransferState = {
    Unscheduled: "unscheduled",
    PendingApproval: "pendingApproval",
    Scheduled: "scheduled",
    Processing: "processing",
    Processed: "processed",
    Failed: "failed",
    Other: "other",
};
