/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../../../errors";
import { ApitureApi } from "../../../..";
export declare class UnprocessableEntity extends errors.ApitureApiError {
    constructor(body: ApitureApi.ProblemResponse);
}
