/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { ApitureApi } from "../../../..";
/**
 * A numeric range for a checking account check number.
 */
export declare type CheckNumberRange = ApitureApi.PositiveIntegerRange;
