"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionSubType = void 0;
exports.TransactionSubType = {
    Check: "check",
    Other: "other",
};
