/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { ApitureApi } from "../../../..";
/**
 * Summary representation of a transaction resource in transactions collections.
 */
export interface TransactionItem extends ApitureApi.AbstractBody, ApitureApi.TransactionFields {
}
