"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionType = void 0;
exports.TransactionType = {
    Balance: "balance",
    Debit: "debit",
    Credit: "credit",
};
