/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Classifies a transaction category as applying to either debit or credit transactions. <strong><code>transactionCategoryType</code></strong> strings may have one of the following [enumerated values](https://dx.apiture.com/docs/api-documentation/concepts/label-groups#enumerations): <table> <tr>
 *   <th>Value</th><th>Description</th>
 * </tr> <tr>
 *     <td><strong><code>credit</code></strong></td><td>Credit: <p>This transaction category applies to credit (expense) transactions.</p>
 * </td>
 *     </tr>
 * <tr>
 *     <td><strong><code>debit</code></strong></td><td>Debit: <p>This transaction category applies to debit (income) transactions.</p>
 * </td>
 *     </tr>
 * </table>
 *
 */
export declare type TransactionCategoryType = "credit" | "debit";
export declare const TransactionCategoryType: {
    readonly Credit: "credit";
    readonly Debit: "debit";
};
