"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionCategoryType = void 0;
exports.TransactionCategoryType = {
    Credit: "credit",
    Debit: "debit",
};
