/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { ApitureApi } from "../../../..";
/**
 * Representation of transaction category resources.
 */
export interface TransactionCategory extends ApitureApi.AbstractBody, ApitureApi.TransactionCategorization {
    type: ApitureApi.TransactionCategoryType;
}
