/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const ProductReference: core.serialization.ObjectSchema<serializers.ProductReference.Raw, ApitureApi.ProductReference>;
export declare namespace ProductReference {
    interface Raw {
        type: serializers.ProductType.Raw;
        code: string;
        label: string;
        description: string;
    }
}
