/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const ProductType: core.serialization.Schema<serializers.ProductType.Raw, ApitureApi.ProductType>;
export declare namespace ProductType {
    type Raw = "savings" | "checking" | "cd" | "ira" | "loan" | "creditCard";
}
