/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AchAccountRisk: core.serialization.Schema<serializers.AchAccountRisk.Raw, ApitureApi.AchAccountRisk>;
export declare namespace AchAccountRisk {
    type Raw = "early" | "normal" | "float" | "sameDay";
}
