/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AddressFields: core.serialization.ObjectSchema<serializers.AddressFields.Raw, ApitureApi.AddressFields>;
export declare namespace AddressFields {
    interface Raw {
        address1: string;
        address2?: string | null;
        locality: string;
        countryCode: string;
    }
}
