/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const Address: core.serialization.ObjectSchema<serializers.Address.Raw, ApitureApi.Address>;
export declare namespace Address {
    interface Raw extends serializers.AddressFields.Raw {
        regionName?: string | null;
        regionCode?: string | null;
        postalCode: string;
    }
}
