/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const CutoffTimeType: core.serialization.Schema<serializers.CutoffTimeType.Raw, ApitureApi.CutoffTimeType>;
export declare namespace CutoffTimeType {
    type Raw = "ach" | "sameDayAch" | "domesticWireTransfer" | "internationalWireTransfer" | "internalTransfer" | "externalTransfer" | "billPay";
}
