/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const CutoffTimes: core.serialization.ObjectSchema<serializers.CutoffTimes.Raw, ApitureApi.CutoffTimes>;
export declare namespace CutoffTimes {
    interface Raw extends serializers.AbstractBody.Raw {
        timeZoneId: serializers.TimeZoneId.Raw;
        items: serializers.CutoffTime.Raw[];
    }
}
