/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const InstitutionLocatorType: core.serialization.Schema<serializers.InstitutionLocatorType.Raw, ApitureApi.InstitutionLocatorType>;
export declare namespace InstitutionLocatorType {
    type Raw = "abaRoutingNumber" | "swiftBicCode" | "ibanAccountNumber";
}
