/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const InstitutionLookupResult: core.serialization.ObjectSchema<serializers.InstitutionLookupResult.Raw, ApitureApi.InstitutionLookupResult>;
export declare namespace InstitutionLookupResult {
    interface Raw extends serializers.AbstractBody.Raw {
        found: boolean;
        institution?: serializers.SimpleInstitution.Raw | null;
        intermediaryInstitutions?: serializers.SimpleInstitution.Raw[] | null;
    }
}
