/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const InstitutionId: core.serialization.Schema<serializers.InstitutionId.Raw, ApitureApi.InstitutionId>;
export declare namespace InstitutionId {
    type Raw = string;
}
