/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const SimpleInstitution: core.serialization.ObjectSchema<serializers.SimpleInstitution.Raw, ApitureApi.SimpleInstitution>;
export declare namespace SimpleInstitution {
    interface Raw {
        name: string;
        address: serializers.Address.Raw;
        locator: string;
        locatorType: serializers.InstitutionLocatorType.Raw;
    }
}
