/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TimeZoneId: core.serialization.Schema<serializers.TimeZoneId.Raw, ApitureApi.TimeZoneId>;
export declare namespace TimeZoneId {
    type Raw = string;
}
