/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferDateRestriction: core.serialization.ObjectSchema<serializers.TransferDateRestriction.Raw, ApitureApi.TransferDateRestriction>;
export declare namespace TransferDateRestriction {
    interface Raw {
        occursOn: string;
        reason: serializers.TransferDateRestrictionType.Raw;
        creditOn?: string | null;
        debitOn?: string | null;
    }
}
