/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferScheduleItem: core.serialization.ObjectSchema<serializers.TransferScheduleItem.Raw, ApitureApi.TransferScheduleItem>;
export declare namespace TransferScheduleItem {
    interface Raw {
        scheduledOn: string;
        effectiveOn: string;
    }
}
