/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferTypeForDateRestrictions: core.serialization.Schema<serializers.TransferTypeForDateRestrictions.Raw, ApitureApi.TransferTypeForDateRestrictions>;
export declare namespace TransferTypeForDateRestrictions {
    type Raw = "internal" | "ach" | "achDebit" | "achCredit" | "domesticWireTransfer" | "internationalWireTransfer";
}
