/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferDateRestrictionType: core.serialization.Schema<serializers.TransferDateRestrictionType.Raw, ApitureApi.TransferDateRestrictionType>;
export declare namespace TransferDateRestrictionType {
    type Raw = "pastDate" | "pastCutoffTime" | "riskRestricted" | "holiday" | "closure" | "other";
}
