/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferDateRestrictions: core.serialization.ObjectSchema<serializers.TransferDateRestrictions.Raw, ApitureApi.TransferDateRestrictions>;
export declare namespace TransferDateRestrictions {
    interface Raw extends serializers.AbstractBody.Raw {
        restrictedDates?: serializers.TransferDateRestriction.Raw[] | null;
        accuracyEndsOn?: string | null;
    }
}
