/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferScheduleDirection: core.serialization.Schema<serializers.TransferScheduleDirection.Raw, ApitureApi.TransferScheduleDirection>;
export declare namespace TransferScheduleDirection {
    type Raw = "debit" | "credit" | "both";
}
