/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AccountAllowsFilter: core.serialization.Schema<serializers.AccountAllowsFilter.Raw, ApitureApi.AccountAllowsFilter>;
export declare namespace AccountAllowsFilter {
    type Raw = "billPay" | "transferFrom" | "transferTo" | "mobileCheckDeposit" | "view" | "viewCards" | "manageCards";
}
