/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AccountJointOwner: core.serialization.ObjectSchema<serializers.AccountJointOwner.Raw, ApitureApi.AccountJointOwner>;
export declare namespace AccountJointOwner {
    interface Raw extends serializers.AbstractBody.Raw {
        id: serializers.ReadOnlyResourceId.Raw;
        name: string;
    }
}
