/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AccountBalances: core.serialization.ObjectSchema<serializers.AccountBalances.Raw, ApitureApi.AccountBalances>;
export declare namespace AccountBalances {
    interface Raw extends serializers.AbstractBody.Raw {
        items: serializers.AccountBalance.Raw[];
    }
}
