/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AccountBalance: core.serialization.ObjectSchema<serializers.AccountBalance.Raw, ApitureApi.AccountBalance>;
export declare namespace AccountBalance {
    interface Raw {
        id: serializers.ReadOnlyResourceId.Raw;
        available?: serializers.CreditOrDebitValue.Raw | null;
        current?: serializers.CreditOrDebitValue.Raw | null;
        updatedAt?: serializers.ReadOnlyTimestamp.Raw | null;
        currentWithPending?: serializers.CreditOrDebitValue.Raw | null;
        incomplete: boolean;
    }
}
