/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AccountPermissions: core.serialization.ObjectSchema<serializers.AccountPermissions.Raw, ApitureApi.AccountPermissions>;
export declare namespace AccountPermissions {
    interface Raw {
        billPay: boolean;
        mobileCheckDeposit: boolean;
        transferFrom: boolean;
        transferTo: boolean;
        view: boolean;
        viewCards: boolean;
        manageCards: boolean;
    }
}
