/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AccountIds: core.serialization.Schema<serializers.AccountIds.Raw, ApitureApi.AccountIds>;
export declare namespace AccountIds {
    type Raw = serializers.ResourceId.Raw[];
}
