/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AccountFields: core.serialization.ObjectSchema<serializers.AccountFields.Raw, ApitureApi.AccountFields>;
export declare namespace AccountFields {
    interface Raw {
        id: serializers.ReadOnlyResourceId.Raw;
        label: string;
        nickname?: serializers.AccountNickname.Raw | null;
        maskedNumber: serializers.MaskedAccountNumber.Raw;
        product: serializers.ProductReference.Raw;
        location: serializers.AccountLocation.Raw;
    }
}
