/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AccountLocation: core.serialization.Schema<serializers.AccountLocation.Raw, ApitureApi.AccountLocation>;
export declare namespace AccountLocation {
    type Raw = "internal" | "external" | "outside";
}
