/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AchSecCode: core.serialization.Schema<serializers.AchSecCode.Raw, ApitureApi.AchSecCode>;
export declare namespace AchSecCode {
    type Raw = "arc" | "boc" | "ccd" | "cie" | "ctx" | "pop" | "ppd" | "rck" | "tel" | "web";
}
