/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const FullAccountPermissions: core.serialization.ObjectSchema<serializers.FullAccountPermissions.Raw, ApitureApi.FullAccountPermissions>;
export declare namespace FullAccountPermissions {
    interface Raw extends serializers.AccountPermissions.Raw {
        manageJointOwners: boolean;
        manageOverdraftAccounts: boolean;
    }
}
