/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const JointOwnerInvitation: core.serialization.ObjectSchema<serializers.JointOwnerInvitation.Raw, ApitureApi.JointOwnerInvitation>;
export declare namespace JointOwnerInvitation {
    interface Raw extends serializers.AbstractBody.Raw, serializers.JointOwnerInvitationFields.Raw {
        id: serializers.ReadOnlyResourceId.Raw;
    }
}
