/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const MaskedAccountNumber: core.serialization.Schema<serializers.MaskedAccountNumber.Raw, ApitureApi.MaskedAccountNumber>;
export declare namespace MaskedAccountNumber {
    type Raw = string;
}
