/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const OverdraftProtection: core.serialization.ObjectSchema<serializers.OverdraftProtection.Raw, ApitureApi.OverdraftProtection>;
export declare namespace OverdraftProtection {
    interface Raw extends serializers.AbstractBody.Raw, serializers.OverdraftProtectionFields.Raw {
        maximumOverdraftAccounts: number;
    }
}
