/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const OverdraftProtectionFields: core.serialization.ObjectSchema<serializers.OverdraftProtectionFields.Raw, ApitureApi.OverdraftProtectionFields>;
export declare namespace OverdraftProtectionFields {
    interface Raw {
        accounts?: unknown | null;
    }
}
