/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const OverdraftProtectionPatch: core.serialization.ObjectSchema<serializers.OverdraftProtectionPatch.Raw, ApitureApi.OverdraftProtectionPatch>;
export declare namespace OverdraftProtectionPatch {
    interface Raw extends serializers.AbstractBody.Raw, serializers.OverdraftProtectionFields.Raw {
    }
}
