"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApitureApiClient = void 0;
const Client_1 = require("./api/resources/accounts/client/Client");
const Client_2 = require("./api/resources/institutions/client/Client");
const Client_3 = require("./api/resources/transactions/client/Client");
const Client_4 = require("./api/resources/transfers/client/Client");
class ApitureApiClient {
    options;
    constructor(options) {
        this.options = options;
    }
    _accounts;
    get accounts() {
        return (this._accounts ??= new Client_1.Accounts(this.options));
    }
    _institutions;
    get institutions() {
        return (this._institutions ??= new Client_2.Institutions(this.options));
    }
    _transactions;
    get transactions() {
        return (this._transactions ??= new Client_3.Transactions(this.options));
    }
    _transfers;
    get transfers() {
        return (this._transfers ??= new Client_4.Transfers(this.options));
    }
}
exports.ApitureApiClient = ApitureApiClient;
