/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "./core";
import { Accounts } from "./api/resources/accounts/client/Client";
import { Institutions } from "./api/resources/institutions/client/Client";
import { Transactions } from "./api/resources/transactions/client/Client";
import { Transfers } from "./api/resources/transfers/client/Client";
export declare namespace ApitureApiClient {
    interface Options {
        environment: string;
        acessToken: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
    }
}
export declare class ApitureApiClient {
    protected readonly options: ApitureApiClient.Options;
    constructor(options: ApitureApiClient.Options);
    protected _accounts: Accounts | undefined;
    get accounts(): Accounts;
    protected _institutions: Institutions | undefined;
    get institutions(): Institutions;
    protected _transactions: Transactions | undefined;
    get transactions(): Transactions;
    protected _transfers: Transfers | undefined;
    get transfers(): Transfers;
}
