"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AchAccountRisk = void 0;
exports.AchAccountRisk = {
    Early: "early",
    Normal: "normal",
    Float: "float",
    SameDay: "sameDay",
};
