"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CutoffTimeType = void 0;
exports.CutoffTimeType = {
    Ach: "ach",
    SameDayAch: "sameDayAch",
    DomesticWireTransfer: "domesticWireTransfer",
    InternationalWireTransfer: "internationalWireTransfer",
    InternalTransfer: "internalTransfer",
    ExternalTransfer: "externalTransfer",
    BillPay: "billPay",
};
