"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferDateRestrictionType = void 0;
exports.TransferDateRestrictionType = {
    PastDate: "pastDate",
    PastCutoffTime: "pastCutoffTime",
    RiskRestricted: "riskRestricted",
    Holiday: "holiday",
    Closure: "closure",
    Other: "other",
};
