"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferTypeForDateRestrictions = void 0;
exports.TransferTypeForDateRestrictions = {
    Internal: "internal",
    Ach: "ach",
    AchDebit: "achDebit",
    AchCredit: "achCredit",
    DomesticWireTransfer: "domesticWireTransfer",
    InternationalWireTransfer: "internationalWireTransfer",
};
