/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AbstractPagedBody: core.serialization.ObjectSchema<serializers.AbstractPagedBody.Raw, ApitureApi.AbstractPagedBody>;
export declare namespace AbstractPagedBody {
    interface Raw extends serializers.AbstractBody.Raw, serializers.AbstractPagedBodyFields.Raw {
        start?: string | null;
    }
}
