/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AbstractPagedBodyFields: core.serialization.ObjectSchema<serializers.AbstractPagedBodyFields.Raw, ApitureApi.AbstractPagedBodyFields>;
export declare namespace AbstractPagedBodyFields {
    interface Raw {
        limit: number;
        nextPage_url?: string | null;
    }
}
