/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AbstractBody: core.serialization.ObjectSchema<serializers.AbstractBody.Raw, ApitureApi.AbstractBody>;
export declare namespace AbstractBody {
    interface Raw {
    }
}
