/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const ApiProblem: core.serialization.ObjectSchema<serializers.ApiProblem.Raw, ApitureApi.ApiProblem>;
export declare namespace ApiProblem {
    interface Raw {
        type?: string | null;
        title?: string | null;
        status?: number | null;
        detail?: string | null;
        instance?: string | null;
        id?: serializers.ReadOnlyResourceId.Raw | null;
        occurredAt?: serializers.ReadOnlyTimestamp.Raw | null;
        problems?: serializers.ApiProblem.Raw[] | null;
        attributes?: Record<string, unknown> | null;
    }
}
