/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const CreditOrDebitValue: core.serialization.Schema<serializers.CreditOrDebitValue.Raw, ApitureApi.CreditOrDebitValue>;
export declare namespace CreditOrDebitValue {
    type Raw = string;
}
