/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const DateRange: core.serialization.Schema<serializers.DateRange.Raw, ApitureApi.DateRange>;
export declare namespace DateRange {
    type Raw = string;
}
