/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const ProblemResponse: core.serialization.ObjectSchema<serializers.ProblemResponse.Raw, ApitureApi.ProblemResponse>;
export declare namespace ProblemResponse {
    interface Raw extends serializers.AbstractBody.Raw, serializers.ApiProblem.Raw {
    }
}
