/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const ReadOnlyTimestamp: core.serialization.Schema<serializers.ReadOnlyTimestamp.Raw, ApitureApi.ReadOnlyTimestamp>;
export declare namespace ReadOnlyTimestamp {
    type Raw = string;
}
