/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const ReadOnlyResourceId: core.serialization.Schema<serializers.ReadOnlyResourceId.Raw, ApitureApi.ReadOnlyResourceId>;
export declare namespace ReadOnlyResourceId {
    type Raw = serializers.ResourceId.Raw;
}
