/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const ResourceId: core.serialization.Schema<serializers.ResourceId.Raw, ApitureApi.ResourceId>;
export declare namespace ResourceId {
    type Raw = string;
}
