"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransferFrequency = void 0;
exports.TransferFrequency = {
    Once: "once",
    Occasional: "occasional",
    Daily: "daily",
    Weekly: "weekly",
    Biweekly: "biweekly",
    Semimonthly: "semimonthly",
    Monthly: "monthly",
    MonthlyFirstDay: "monthlyFirstDay",
    MonthlyLastDay: "monthlyLastDay",
    Bimonthly: "bimonthly",
    Quarterly: "quarterly",
    Semiyearly: "semiyearly",
    Yearly: "yearly",
};
