/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { ApitureApi } from "../../../..";
/**
 * An array of account IDs.
 */
export declare type AccountIds = ApitureApi.ResourceId[];
