"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountLocation = void 0;
exports.AccountLocation = {
    Internal: "internal",
    External: "external",
    Outside: "outside",
};
