"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountAllowsFilter = void 0;
exports.AccountAllowsFilter = {
    BillPay: "billPay",
    TransferFrom: "transferFrom",
    TransferTo: "transferTo",
    MobileCheckDeposit: "mobileCheckDeposit",
    View: "view",
    ViewCards: "viewCards",
    ManageCards: "manageCards",
};
