"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AchSecCode = void 0;
exports.AchSecCode = {
    Arc: "arc",
    Boc: "boc",
    Ccd: "ccd",
    Cie: "cie",
    Ctx: "ctx",
    Pop: "pop",
    Ppd: "ppd",
    Rck: "rck",
    Tel: "tel",
    Web: "web",
};
