/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { ApitureApi } from "../../../..";
/**
 * A joint owner invitation.
 */
export interface JointOwnerInvitation extends ApitureApi.AbstractBody, ApitureApi.JointOwnerInvitationFields {
    id: ApitureApi.ReadOnlyResourceId;
}
