/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import { ApitureApi } from "../../../../..";
import * as core from "../../../../../core";
export declare const TransferPatch: core.serialization.Schema<serializers.TransferPatch.Raw, Omit<ApitureApi.TransferPatch, "challenge">>;
export declare namespace TransferPatch {
    interface Raw extends serializers.AbstractBody.Raw, serializers.TransferFields.Raw {
        schedule?: serializers.TransferSchedule.Raw | null;
    }
}
