/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const AmountRange: core.serialization.Schema<serializers.AmountRange.Raw, ApitureApi.AmountRange>;
export declare namespace AmountRange {
    type Raw = string;
}
