/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const CheckNumberRange: core.serialization.Schema<serializers.CheckNumberRange.Raw, ApitureApi.CheckNumberRange>;
export declare namespace CheckNumberRange {
    type Raw = serializers.PositiveIntegerRange.Raw;
}
