/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransactionCheck: core.serialization.ObjectSchema<serializers.TransactionCheck.Raw, ApitureApi.TransactionCheck>;
export declare namespace TransactionCheck {
    interface Raw {
        number: number;
        imageFront_url?: string | null;
        imageBack_url?: string | null;
    }
}
