/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransactionCategorization: core.serialization.ObjectSchema<serializers.TransactionCategorization.Raw, ApitureApi.TransactionCategorization>;
export declare namespace TransactionCategorization {
    interface Raw {
        label: serializers.TransactionCategoryLabel.Raw;
        id: string;
    }
}
