/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransactionMerchant: core.serialization.ObjectSchema<serializers.TransactionMerchant.Raw, ApitureApi.TransactionMerchant>;
export declare namespace TransactionMerchant {
    interface Raw {
        name?: string | null;
        website_url?: string | null;
        logo_url?: string | null;
    }
}
