/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const Transactions: core.serialization.ObjectSchema<serializers.Transactions.Raw, ApitureApi.Transactions>;
export declare namespace Transactions {
    interface Raw extends serializers.AbstractPagedBody.Raw {
        items?: serializers.TransactionItem.Raw[] | null;
        count?: number | null;
    }
}
