/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransactionFields: core.serialization.ObjectSchema<serializers.TransactionFields.Raw, ApitureApi.TransactionFields>;
export declare namespace TransactionFields {
    interface Raw {
        id: string;
        type: serializers.TransactionType.Raw;
        subtype: serializers.TransactionSubType.Raw;
        occurredOn: string;
        createdOn?: string | null;
        postedOn?: string | null;
        amount: serializers.CreditOrDebitValue.Raw;
        posted?: boolean | null;
        balance?: serializers.CreditOrDebitValue.Raw | null;
        memo?: string | null;
        description?: string | null;
        category?: serializers.TransactionCategorization.Raw | null;
        merchant?: serializers.TransactionMerchant.Raw | null;
        check?: serializers.TransactionCheck.Raw | null;
    }
}
