/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransactionItem: core.serialization.ObjectSchema<serializers.TransactionItem.Raw, ApitureApi.TransactionItem>;
export declare namespace TransactionItem {
    interface Raw extends serializers.AbstractBody.Raw, serializers.TransactionFields.Raw {
    }
}
