/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransactionSubType: core.serialization.Schema<serializers.TransactionSubType.Raw, ApitureApi.TransactionSubType>;
export declare namespace TransactionSubType {
    type Raw = "check" | "other";
}
