/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransactionCategoryType: core.serialization.Schema<serializers.TransactionCategoryType.Raw, ApitureApi.TransactionCategoryType>;
export declare namespace TransactionCategoryType {
    type Raw = "credit" | "debit";
}
