/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransactionCategoryLabel: core.serialization.Schema<serializers.TransactionCategoryLabel.Raw, ApitureApi.TransactionCategoryLabel>;
export declare namespace TransactionCategoryLabel {
    type Raw = string;
}
