/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransactionType: core.serialization.Schema<serializers.TransactionType.Raw, ApitureApi.TransactionType>;
export declare namespace TransactionType {
    type Raw = "balance" | "debit" | "credit";
}
