/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransactionCategory: core.serialization.ObjectSchema<serializers.TransactionCategory.Raw, ApitureApi.TransactionCategory>;
export declare namespace TransactionCategory {
    interface Raw extends serializers.AbstractBody.Raw, serializers.TransactionCategorization.Raw {
        type: serializers.TransactionCategoryType.Raw;
    }
}
