/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const ChallengeToken: core.serialization.Schema<serializers.ChallengeToken.Raw, ApitureApi.ChallengeToken>;
export declare namespace ChallengeToken {
    type Raw = string;
}
