/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const MonetaryValue: core.serialization.Schema<serializers.MonetaryValue.Raw, ApitureApi.MonetaryValue>;
export declare namespace MonetaryValue {
    type Raw = string;
}
