/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TimestampFields: core.serialization.ObjectSchema<serializers.TimestampFields.Raw, ApitureApi.TimestampFields>;
export declare namespace TimestampFields {
    interface Raw {
        createdAt?: string | null;
        updatedAt?: string | null;
    }
}
