/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const Transfer: core.serialization.ObjectSchema<serializers.Transfer.Raw, ApitureApi.Transfer>;
export declare namespace Transfer {
    interface Raw extends serializers.AbstractBody.Raw, serializers.TransferItem.Raw {
    }
}
