/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const Transfers: core.serialization.ObjectSchema<serializers.Transfers.Raw, ApitureApi.Transfers>;
export declare namespace Transfers {
    interface Raw extends serializers.AbstractPagedBody.Raw {
        items: serializers.TransferItem.Raw[];
        count?: number | null;
    }
}
