/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferState: core.serialization.Schema<serializers.TransferState.Raw, ApitureApi.TransferState>;
export declare namespace TransferState {
    type Raw = "unscheduled" | "pendingApproval" | "scheduled" | "processing" | "processed" | "failed" | "other";
}
