/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferRecurrenceType: core.serialization.Schema<serializers.TransferRecurrenceType.Raw, ApitureApi.TransferRecurrenceType>;
export declare namespace TransferRecurrenceType {
    type Raw = "fixed" | "variable";
}
