/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferFields: core.serialization.ObjectSchema<serializers.TransferFields.Raw, ApitureApi.TransferFields>;
export declare namespace TransferFields {
    interface Raw {
        amount?: serializers.MonetaryValue.Raw | null;
        sourceAccount?: serializers.TransferAccountReference.Raw | null;
        targetAccount?: serializers.TransferAccountReference.Raw | null;
        memo?: string | null;
    }
}
