/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferItem: core.serialization.ObjectSchema<serializers.TransferItem.Raw, ApitureApi.TransferItem>;
export declare namespace TransferItem {
    interface Raw extends serializers.TransferFields.Raw, serializers.TimestampFields.Raw {
        id: serializers.ReadOnlyResourceId.Raw;
        schedule: serializers.TransferItemSchedule.Raw;
        state: serializers.TransferState.Raw;
        processedAt?: string | null;
        updatedBy?: string | null;
    }
}
