/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferItemSchedule: core.serialization.ObjectSchema<serializers.TransferItemSchedule.Raw, ApitureApi.TransferItemSchedule>;
export declare namespace TransferItemSchedule {
    interface Raw extends serializers.TransferSchedule.Raw {
        debitsOn?: string | null;
        creditsOn?: string | null;
    }
}
