/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import { ApitureApi } from "../../../..";
import * as core from "../../../../core";
export declare const TransferSchedule: core.serialization.ObjectSchema<serializers.TransferSchedule.Raw, ApitureApi.TransferSchedule>;
export declare namespace TransferSchedule {
    interface Raw {
        scheduledOn?: string | null;
        recurrenceType?: serializers.TransferRecurrenceType.Raw | null;
        frequency: serializers.TransferFrequency.Raw;
        endsOn?: string | null;
        count?: number | null;
        amountLimit?: serializers.MonetaryValue.Raw | null;
    }
}
